# Using version `0.10.0`:
include:
  - component: gitlab.com/components/opentofu/full-pipeline@0.10.0
    inputs:
      opentofu_version: 1.6.1
      auto_define_backend: true

stages: [validate, test, build, deploy, cleanup]
