stages:
  - validate
  - plan
  - apply
  - destroy

variables:
  TOFU_VERSION: "1.7.2"  # or latest OpenTofu version
  TOFU_BINARY: "/usr/local/bin/tofu"

#before_script:
#  - curl -sSL https://get.opentofu.org/install | bash
#  - export PATH=$HOME/.opentofu/bin:$PATH
#  - tofu --version

validate:
  stage: validate
  script:
    - gitlab-tofu init
    - gitlab-tofu validate

plan:
  stage: plan
  script:
    - gitlab-tofu init
    - gitlab-tofu plan -out=tfplan
  artifacts:
    paths:
      - tfplan

apply:
  stage: apply
  when: manual  # Prevent automatic apply
  script:
    - gitlab-tofu init
    - gitlab-tofu apply -auto-approve tfplan

destroy:
  stage: destroy
  when: manual
  script:
    - gitlab-tofu init
    - gitlab-tofu destroy -auto-approve