on: 
  push: 
    branches:
      - main
  workflow_dispatch:

jobs:
  infrastructure-setup:
    defaults:
      run:
        working-directory: infrastructure
    name: Format, validate and plan infrastructure
    runs-on: ubuntu-latest
    steps:
    - uses: opentofu/setup-opentofu@v1
    
    - name: OpenTofu fmt
      id: fmt
      run: tofu fmt -check
      continue-on-error: true
    
    - name: OpenTofu Init
      id: init
      run: tofu init
    
    - name: OpenTofu Validate
      id: validate
      run: tofu validate -no-color
    
    - name: OpenTofu Plan
      id: plan
      run: tofu plan -no-color
